routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('website.master');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard','DashboardController@index')->name('dashboard');

// Users
Route::resource('users','UserController');


// Roles
Route::resource('roles','RoleController');

// Permissions
Route::resource('permissions','PermissionsController');

// Branches
Route::resource('branch','BranchController');

// Branches
Route::resource('disclaimer','DisclaimerController');

// Companies
Route::resource('company','CompanyController');

// Categories
Route::resource('category','CategoryController');

//Sub Categories
Route::resource('subcategory','SubCategoryController');

//Blogs
Route::resource('blog','BlogsController');
Route::post('photoupload','BlogsController@uploadPhoto')->name('PhotoUpload');

// cart controller
Route::resource('cart', 'CartController');
Route::get('getcartcount','CartController@getCartCount');
Route::post('updatecart','CartController@updateCartItems');
//Bannerimage
Route::resource('bannerimage','BannerImageController'); 

//  Brand Image
Route::resource('brandimage','BrandController');

// Items
Route::resource('item','ItemController');


// Offers
Route::resource('offer','OfferController');

// Videos
Route::resource('video','VideoController');

// Customers
Route::resource('customer','CustomerController');
Route::post('search_customer','CustomerController@searchCustomer');

// Stock
Route::resource('stock','StockController');

// Installment Plans
Route::resource('installmentplan','InstallmentPlansController');

// Customer Application Form
Route::resource('customerapplicationform','CustomerApplicationFormController');

// Contact Us Form
Route::resource('contactus','ContactusController');
Route::post('submit','ContactusController@store');

// Review
Route::resource('review','ReviewController');

Route::resource('userstatus','ReviewController@changestatus');
Route::post('reviewform','ReviewController@store');

// website Related Routes
Route::get('check_user_login', function () {
    if(Auth::check()){
        return true;
    }
    else{
        return false;
    }
});
Route::post('customer/login','CustomerController@login');
Route::get('logoutcustomer','CustomerController@logout')->name('logoutcustomer');
Route::get('getcategory','WebsiteController@getCategory');
Route::get('getitem', 'WebsiteController@getItem');
Route::get('getblog', 'WebsiteController@getBlog');
Route::get('getfeatureditems', 'WebsiteController@getfeatureditems');
Route::get('getdeal', 'WebsiteController@getdeals');
Route::get('getnewarrival', 'WebsiteController@getnewarrivals');
Route::get('getonsale', 'WebsiteController@getonsales');
Route::get('getoffers', 'WebsiteController@getnewoffer');
Route::get('getfeedbacks', 'WebsiteController@feedbacks');
Route::get('getfooter', 'WebsiteController@getFooter');
Route::get('getcompany', 'WebsiteController@getCompany');
Route::get('getoffer', 'WebsiteController@getOffer');
Route::get('getpopularCategoryItems', 'WebsiteController@getpopularCategoryItems');
Route::get('getvedio',  'WebsiteController@getVideo');
Route::get('itemdetail', 'WebsiteController@ItemDetail');
Route::get('itemReviews', 'WebsiteController@itemReviews');
Route::get('blogdetail/{id}', 'WebsiteController@blogDetail');
Route::get('userstatus','ReviewController@changestatus');
Route::post('under_review','ReviewController@under_review');
Route::post('orderstatuss','OrderController@orderstatus');
Route::resource('footerimage','FooterController');
Route::resource('wishlist', 'WishlistController');
Route::resource('feedback', 'FeedbackController');
Route::post('change_status', 'FeedbackController@status');
Route::get('getbanners','WebsiteController@getBanners');
Route::get('getuser' ,'WebsiteController@getUsers');
Route::post('check' ,'WebsiteController@checkLogin');
Route::resource('order_detail', 'OrderController');
Route::post('manual_detail', 'OrderController@manualOrder');
Route::get('addorder','OrderController@addOrder')->name("addOrder");
Route::post('getuserdetail','OrderController@getUserDetail');
Route::post('getproduct','OrderController@getProduct');
Route::post('getprice','WebsiteController@filterByRange');
Route::get('/path/{offers?}', 'AppController@index')->where('offers', '[\/\w\.-]*');
Route::resource('remark', 'RemarkController');
Route::resource('callrequest', 'CallRequestController');
Route::post('addremark','CallRequestController@addRemark');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Branch;
use App\Models\Company;
use App\Models\Category;

class DashboardController extends Controller
{
    // Checking User is login or not
    public function __construct(){
        $this->middleware('auth');
    }

    public function index(){
        // Fetching all related data
        $users = User::select('id')->get();
        $branches = Branch::select('id')->get();
        $companies = Company::select('id')->get();
        $categories = Category::select('id')->get();
        return view('dashboard.dashboard',compact('users','branches','companies','categories'));
    }
}

resources/views/dashboard/dashboard.blade.php
@extends('layout.master')
@section('content')
    <div class="content">
        <div class="container-fluid pt-2">
            {{-- Checking User Have permission --}}
            @can('View Dashboard')
                <div class="row">
                    {{-- Users Info --}}
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{count($users)}}</h3>
                                <p>Users</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-users"></i>
                            </div>
                            <a href="{{ route('users.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    {{-- End Users Info --}}
                    {{-- Branches Info --}}
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{count($branches)}}</h3>
                                <p>Branches</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-code-branch"></i>
                            </div>
                            <a href="{{ route('branch.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    {{-- End Branches Info --}}
                    {{-- Companies Info --}}
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{count($companies)}}</h3>
                                <p>Companies</p>
                            </div>
                            <div class="icon">
                                <i class="far fa-building"></i>
                            </div>
                            <a href="{{ route('company.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    {{-- End Companies Info --}}
                    {{-- Categories Info --}}
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{count($categories)}}</h3>
                                <p>Categories</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-list-alt"></i>
                            </div>
                            <a href="{{ route('category.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    {{-- End Categories Info --}}
                </div>
            @endcan
            {{-- End Checking User Have permission --}}
        </div>
    </div>
@endsection