routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('website.master');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard','DashboardController@index')->name('dashboard');

// Users
Route::resource('users','UserController');


// Roles
Route::resource('roles','RoleController');

// Permissions
Route::resource('permissions','PermissionsController');

// Branches
Route::resource('branch','BranchController');

// Branches
Route::resource('disclaimer','DisclaimerController');

// Companies
Route::resource('company','CompanyController');

// Categories
Route::resource('category','CategoryController');

//Sub Categories
Route::resource('subcategory','SubCategoryController');

//Blogs
Route::resource('blog','BlogsController');
Route::post('photoupload','BlogsController@uploadPhoto')->name('PhotoUpload');

// cart controller
Route::resource('cart', 'CartController');
Route::get('getcartcount','CartController@getCartCount');
Route::post('updatecart','CartController@updateCartItems');
//Bannerimage
Route::resource('bannerimage','BannerImageController'); 

//  Brand Image
Route::resource('brandimage','BrandController');

// Items
Route::resource('item','ItemController');


// Offers
Route::resource('offer','OfferController');

// Videos
Route::resource('video','VideoController');

// Customers
Route::resource('customer','CustomerController');
Route::post('search_customer','CustomerController@searchCustomer');

// Stock
Route::resource('stock','StockController');

// Installment Plans
Route::resource('installmentplan','InstallmentPlansController');

// Customer Application Form
Route::resource('customerapplicationform','CustomerApplicationFormController');

// Contact Us Form
Route::resource('contactus','ContactusController');
Route::post('submit','ContactusController@store');

// Review
Route::resource('review','ReviewController');

Route::resource('userstatus','ReviewController@changestatus');
Route::post('reviewform','ReviewController@store');

// website Related Routes
Route::get('check_user_login', function () {
    if(Auth::check()){
        return true;
    }
    else{
        return false;
    }
});
Route::post('customer/login','CustomerController@login');
Route::get('logoutcustomer','CustomerController@logout')->name('logoutcustomer');
Route::get('getcategory','WebsiteController@getCategory');
Route::get('getitem', 'WebsiteController@getItem');
Route::get('getblog', 'WebsiteController@getBlog');
Route::get('getfeatureditems', 'WebsiteController@getfeatureditems');
Route::get('getdeal', 'WebsiteController@getdeals');
Route::get('getnewarrival', 'WebsiteController@getnewarrivals');
Route::get('getonsale', 'WebsiteController@getonsales');
Route::get('getoffers', 'WebsiteController@getnewoffer');
Route::get('getfeedbacks', 'WebsiteController@feedbacks');
Route::get('getfooter', 'WebsiteController@getFooter');
Route::get('getcompany', 'WebsiteController@getCompany');
Route::get('getoffer', 'WebsiteController@getOffer');
Route::get('getpopularCategoryItems', 'WebsiteController@getpopularCategoryItems');
Route::get('getvedio',  'WebsiteController@getVideo');
Route::get('itemdetail', 'WebsiteController@ItemDetail');
Route::get('itemReviews', 'WebsiteController@itemReviews');
Route::get('blogdetail/{id}', 'WebsiteController@blogDetail');
Route::get('userstatus','ReviewController@changestatus');
Route::post('under_review','ReviewController@under_review');
Route::post('orderstatuss','OrderController@orderstatus');
Route::resource('footerimage','FooterController');
Route::resource('wishlist', 'WishlistController');
Route::resource('feedback', 'FeedbackController');
Route::post('change_status', 'FeedbackController@status');
Route::get('getbanners','WebsiteController@getBanners');
Route::get('getuser' ,'WebsiteController@getUsers');
Route::post('check' ,'WebsiteController@checkLogin');
Route::resource('order_detail', 'OrderController');
Route::post('manual_detail', 'OrderController@manualOrder');
Route::get('addorder','OrderController@addOrder')->name("addOrder");
Route::post('getuserdetail','OrderController@getUserDetail');
Route::post('getproduct','OrderController@getProduct');
Route::post('getprice','WebsiteController@filterByRange');
Route::get('/path/{offers?}', 'AppController@index')->where('offers', '[\/\w\.-]*');
Route::resource('remark', 'RemarkController');
Route::resource('callrequest', 'CallRequestController');
Route::post('addremark','CallRequestController@addRemark');

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    use HasFactory;
    protected $fillable = ['id','name','category_id'];


    public function categories()
    {
        return $this->belongsTo(Category::class,'category_id');
    }
    public function SUbCateSave($arrData)
    {
        SubCategory::create($arrData);
        return true;
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\SubCategory;
use Auth;
use DataTables;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $users = SubCategory::select('id', 'name', 'category_id')->with('categories');

            return DataTables::eloquent($users)
                ->addColumn('action', function ($data) {

                    $button = '';
                    if (Auth::user()->can('Edit SubCategory')) {
                        $button .= '<i class="fas fa-edit edit" onclick=edit(' . $data->id . ') style="cursor:pointer" title="Edit"></i>';
                    }

                    if (Auth::user()->can('Delete SubCategory')) {
                        $button .= '<i class="fas fa-trash delete text-danger"  onclick=deleterow("' . $data->id . '") style="cursor:pointer;margin-left:3px" title="Delete"></i>';
                    }

                    return $button;

                })
                ->addColumn('c_name', function ($data) {
                    if (isset($data->categories->name)) {
                        $cate = $data->categories->name;
                    } else {
                        $cate = '';
                    }
                    return $cate;

                })->rawColumns(array("c_name", "action"))->make(true);

        }
        $categories = Category::select('id', 'name')->get();

        return view('subCategory.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        try {
            // Validating Request Data
            $this->validate($request, [
                'name' => 'required',
                // 'code' => 'required',
                'category_id' => 'required',
            ]);

            $data = $request->all();

            $data['created_by'] = Auth::id();

            // Creating new record
            $category = new SubCategory;
            $dds = $category->SUbCateSave($data);

            return ['code' => '200', 'message' => 'success'];
        } catch (\Exception  | ValidationException $e) {
            if ($e instanceof ValidationException) {
                return ['code' => '200', 'errors' => $e->errors()];
            } else {
                return ['code' => '200', 'error_message' => $e->getMessage()];
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(SubCategory $subcategory)
    {
        return $subcategory->toArray();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SubCategory $subcategory)
    {
        try {
            // Validating Request Data
            $this->validate($request, [
                'name' => 'required',
                // 'code' => 'required',
                'category_id' => 'required',
            ]);

            $data = $request->all();

            $data['updated_by'] = Auth::id();

            // Updating existing record
            $subcategory->fill($data)->save();

            return ['code' => '200', 'message' => 'success'];
        } catch (\Exception  | ValidationException $e) {
            if ($e instanceof ValidationException) {
                return ['code' => '200', 'errors' => $e->errors()];
            } else {
                return ['code' => '200', 'error_message' => $e->getMessage()];
            }
        }}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(SubCategory $subcategory)
    {
        try {
            // Model Binding
            $subcategory->delete();

            return ['code' => '200', 'message' => 'success'];
        } catch (\Exception $e) {
            return ['code' => '200', 'error_message' => $e->getMessage()];
        }
    }
}

resources/views/subCategory/index.blade.php
@extends('layout.master')
@section('content')
    <!-- All Records -->
    <div class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header row">
                    <h3 class="col-10">All Sub Categories</h3>
                    {{-- Checking permission --}}
                    @can('Add Category')
                        <div class="col-2">
                            <button type="button" class="btn btn-primary float-right" data-toggle="modal"
                                data-target="#add_new_modal">Add New</button>
                        </div>
                    @endcan
                    {{-- End Checking permission --}}
                </div>
                <div class="card-body">
                    <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap"
                        style="width: 100%;">
                        <thead>
                            <tr>
                                <th>Sub Category</th>
                                {{-- <th>Code</th> --}}
                                <th>Category</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Records -->
    <!-- Add Record -->
    <div id="add_new_modal" class="modal fade" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered" permission="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Sub Category</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form id="add">
                    <div class="card-body">
                        @csrf
                        {{-- <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="permission_name">Code:</label>
                                    <input type="text" name="code" class="form-control" placeholder="Enter  Code" />
                                </div>
                            </div>
                        </div> --}}
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="plans"> Categories:</label>
                                    <select name="category_id" id="" class="form-control">
                                        <option value="">--Select--</option>
                                        @foreach ($categories as $key => $value)
                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="permission_name">Sub Category:</label>
                                    <input type="text" name="name" class="form-control"
                                        placeholder="Enter Sub-Category" />
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer form_footer text-right">
                        <button type="submit" class="btn btn-success"><i class="far fa-save"></i> Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- End Add Record -->
    <!-- Edit Record -->
    <div id="edit_modal" class="modal fade" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered" permission="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Update SubCategory</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form class="editform">
                    <div class="card-body">
                        @csrf
                        @method('PUT')
                        {{-- <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="permission_name">Code:</label>
                                    <input type="text" name="code" class="form-control" placeholder="Enter  Code"
                                        id="editcode" />
                                </div>
                            </div>
                        </div> --}}
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="permission_name">Sub Category:</label>
                                    <input type="text" name="name" class="form-control" placeholder="Enter  Name"
                                        id="editname" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="plans">Category:</label>
                                    <select class="form-control" name="category_id" id="editcategories">
                                        <option value="">--Select--</option>
                                        @foreach ($categories as $key => $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="card-footer form_footer text-right">
                            <button type="submit" class="btn btn-success" id="updatebutton"><i class="far fa-save"></i>
                                Save Changes</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
    <!-- End Edit Record -->
@endsection
@section('scripts')
    <script>
        var datatable;
        var rowid;
        $(document).ready(function() {
            // Fetching Records
            datatable = $("#datatable").DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ordering: false,
                ajax: {
                    url: "{{ url('subcategory') }}",
                    method: "get",
                },
                columns: [{
                        data: "name"
                    },
                    // {
                    //     data: "code"
                    // },
                    {
                        data: "c_name"
                    },
                    {
                        data: "action"
                    },
                ],
            });
            // End Fetching Records
            // Adding Record
            $("#add").submit(function(e) {
                e.preventDefault();
                $.ajax({
                    url: "{{ route('subcategory.store') }}",
                    type: "post",
                    data: new FormData(this),
                    processData: false,
                    contentType: false,
                    responsive: true,
                    success: function(success) {
                        if (success.errors) {
                            $.each(success.errors, function(index, value) {
                                toastr.error(value);
                            });
                        } else if (success.error_message) {
                            toastr.error(
                                'An error has been occured! Please Contact Administrator.');
                        } else {
                            datatable.ajax.reload();
                            document.getElementById("add").reset();
                            $("#add_new_modal").modal("hide");
                            toastr.success('Sub Category has been Added Successfully!');
                        }

                    },
                    error: function(response) {
                        toastr.error(
                            'Error! Sub Category could not be created due to some reasons.');
                    },
                });
            });
            // End Adding Record
            // Updating Record
            $(".editform").on("submit", function(e) {
                e.preventDefault();
                $.ajax({
                    url: "{{ url('subcategory') }}" + "/" + rowid,
                    type: "post",
                    data: new FormData(this),
                    processData: false,
                    contentType: false,
                    success: function(success) {
                        if (success.errors) {
                            $.each(success.errors, function(index, value) {
                                toastr.error(value);
                            });
                        } else if (success.error_message) {
                            toastr.error(
                                'An error has been occured! Please Contact Administrator.');
                        } else {
                            $(".editform").off("submit", "**");
                            datatable.ajax.reload();
                            $("#edit_modal").modal("hide");
                            toastr.success('SubCategory has been Updated Successfully!');
                        }

                    },
                    error: function(response) {
                        toastr.error(
                            'Error! Category could not be updated due to some reasons.');
                    },
                });
            });
            // End Updating Record
            // Initializing Select2
            // $(".select2").select2({
            //     placeholder: "Select Installment Plans",
            //     closeOnSelect: true,
            //     allowClear: true,
            // });
            // End Initializing Select2
        });
        // Fetching existing data to edit
        function edit(id) {
            rowid = id;
            $.ajax({
                url: "{{ url('subcategory') }}" + "/" + id + "/edit",
                type: "get",
                success: function(success) {
                    // $("#editcode").val(success.code);
                    $("#editname").val(success.name);
                    $("#editcategories").val(success.category_id)
                    $("#edit_modal").modal("show");
                },
            });
        }
        // End Fetching existing data to edit
        // Deleting Record
        function deleterow(id) {
            if (confirm("Do you really want to delete this Category?")) {
                $.ajax({
                    url: "{{ url('subcategory') }}" + "/" + id,
                    type: "delete",
                    data: {
                        _token: "{{ csrf_token() }}",
                    },
                    success: function(success) {
                        if (success.error_message) {
                            toastr.error('An error has been occured! Please Contact Administrator.');
                        } else {
                            datatable.ajax.reload();
                            toastr.success('Category has been Deleted Successfully!');
                        }
                    },
                    error: function(response) {
                        toastr.error('Error! Category could not be deleted due to some reasons.');
                    },
                });
            }
        }
        // End Deleting Record
    </script>
@endsection