routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('website.master');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard','DashboardController@index')->name('dashboard');

// Users
Route::resource('users','UserController');


// Roles
Route::resource('roles','RoleController');

// Permissions
Route::resource('permissions','PermissionsController');

// Branches
Route::resource('branch','BranchController');

// Branches
Route::resource('disclaimer','DisclaimerController');

// Companies
Route::resource('company','CompanyController');

// Categories
Route::resource('category','CategoryController');

//Sub Categories
Route::resource('subcategory','SubCategoryController');

//Blogs
Route::resource('blog','BlogsController');
Route::post('photoupload','BlogsController@uploadPhoto')->name('PhotoUpload');

// cart controller
Route::resource('cart', 'CartController');
Route::get('getcartcount','CartController@getCartCount');
Route::post('updatecart','CartController@updateCartItems');
//Bannerimage
Route::resource('bannerimage','BannerImageController'); 

//  Brand Image
Route::resource('brandimage','BrandController');

// Items
Route::resource('item','ItemController');


// Offers
Route::resource('offer','OfferController');

// Videos
Route::resource('video','VideoController');

// Customers
Route::resource('customer','CustomerController');
Route::post('search_customer','CustomerController@searchCustomer');

// Stock
Route::resource('stock','StockController');

// Installment Plans
Route::resource('installmentplan','InstallmentPlansController');

// Customer Application Form
Route::resource('customerapplicationform','CustomerApplicationFormController');

// Contact Us Form
Route::resource('contactus','ContactusController');
Route::post('submit','ContactusController@store');

// Review
Route::resource('review','ReviewController');

Route::resource('userstatus','ReviewController@changestatus');
Route::post('reviewform','ReviewController@store');

// website Related Routes
Route::get('check_user_login', function () {
    if(Auth::check()){
        return true;
    }
    else{
        return false;
    }
});
Route::post('customer/login','CustomerController@login');
Route::get('logoutcustomer','CustomerController@logout')->name('logoutcustomer');
Route::get('getcategory','WebsiteController@getCategory');
Route::get('getitem', 'WebsiteController@getItem');
Route::get('getblog', 'WebsiteController@getBlog');
Route::get('getfeatureditems', 'WebsiteController@getfeatureditems');
Route::get('getdeal', 'WebsiteController@getdeals');
Route::get('getnewarrival', 'WebsiteController@getnewarrivals');
Route::get('getonsale', 'WebsiteController@getonsales');
Route::get('getoffers', 'WebsiteController@getnewoffer');
Route::get('getfeedbacks', 'WebsiteController@feedbacks');
Route::get('getfooter', 'WebsiteController@getFooter');
Route::get('getcompany', 'WebsiteController@getCompany');
Route::get('getoffer', 'WebsiteController@getOffer');
Route::get('getpopularCategoryItems', 'WebsiteController@getpopularCategoryItems');
Route::get('getvedio',  'WebsiteController@getVideo');
Route::get('itemdetail', 'WebsiteController@ItemDetail');
Route::get('itemReviews', 'WebsiteController@itemReviews');
Route::get('blogdetail/{id}', 'WebsiteController@blogDetail');
Route::get('userstatus','ReviewController@changestatus');
Route::post('under_review','ReviewController@under_review');
Route::post('orderstatuss','OrderController@orderstatus');
Route::resource('footerimage','FooterController');
Route::resource('wishlist', 'WishlistController');
Route::resource('feedback', 'FeedbackController');
Route::post('change_status', 'FeedbackController@status');
Route::get('getbanners','WebsiteController@getBanners');
Route::get('getuser' ,'WebsiteController@getUsers');
Route::post('check' ,'WebsiteController@checkLogin');
Route::resource('order_detail', 'OrderController');
Route::post('manual_detail', 'OrderController@manualOrder');
Route::get('addorder','OrderController@addOrder')->name("addOrder");
Route::post('getuserdetail','OrderController@getUserDetail');
Route::post('getproduct','OrderController@getProduct');
Route::post('getprice','WebsiteController@filterByRange');
Route::get('/path/{offers?}', 'AppController@index')->where('offers', '[\/\w\.-]*');
Route::resource('remark', 'RemarkController');
Route::resource('callrequest', 'CallRequestController');
Route::post('addremark','CallRequestController@addRemark');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $guarded= [];


    public function items()
    {
        return $this->hasMany(Item::class);
    }

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Company;
use Illuminate\Validation\ValidationException;
use DataTables;
use Auth;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // Checking User is login or not
    public function __construct(){
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        if($request->ajax())
        {
            $users=Company::select('id','name');
            return  DataTables::eloquent($users)->addColumn('action',function($data){
                $button = '';
                if(Auth::user()->can('Edit Company'))
                $button .='<i class="fas fa-edit edit" id="'.$data->id.'" data-name="'.$data->name.'"  style="cursor:pointer" title="Edit">';
                if(Auth::user()->can('Delete Company'))
                $button .= '</i><i class="fas fa-trash delete text-danger"  onclick=deleterow("'.$data->id.'") style="cursor:pointer;margin-left:3px" title="Delete"></i>';
            return $button;
            })->make(true);
    
        }
        return view('company.index');

    }

  
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        try{
            // Validating Request Data
            $this->validate($request, [
                'name' => 'required | unique:companies,name',
            ]);

            $data = $request->all();

            $data['created_by'] = Auth::id();

            // Creating new record
            Company::create($data);

            return ['code'=>'200','message'=>'success'];
        }
        catch(\Exception | ValidationException $e){
            if($e instanceof ValidationException){
                return ['code'=>'200','errors' => $e->errors()];
            }
            else{
                return ['code'=>'200','error_message'=>$e->getMessage()];
            }
        }  
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        try{
            // Validating Request Data
            $this->validate($request, [
                'name' => 'required | unique:companies,name,'.$company->id,
            ]);

            $data = $request->all();

            $data['updated_by'] = Auth::id();

            // Updating existing record
            $company->fill($data)->save();

            return ['code'=>'200','message'=>'success'];
        }
        catch(\Exception | ValidationException $e){
            if($e instanceof ValidationException){
                return ['code'=>'200','errors' => $e->errors()];
            }
            else{
                return ['code'=>'200','error_message'=>$e->getMessage()];
            }
        } 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        try{
            // Model Binding
            $company->delete();

            return ['code'=>'200','message'=>'success'];
        }
        catch(\Exception $e){
            return ['code'=>'200','error_message'=>$e->getMessage()];
        }
    }
}

resources/views/company/index.blade.php
@extends('layout.master') 
@section('content')
<!-- All Records -->
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header row">
                <h3 class="col-10">All Companies</h3>
                {{-- Checking permission --}}
                @can('Add Company')
                <div class="col-2">
                    <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#add_new_modal">Add New</button>
                </div>
                @endcan
                {{-- End Checking permission --}}
            </div>
            <div class="card-body">
                <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap" style="width: 100%;">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- End All Records -->
<!-- Add Record -->
<div id="add_new_modal" class="modal fade" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-dialog-centered" permission="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Company</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form id="add">
                <div class="card-body">
                    @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="permission_name">Name:</label>
                                <input type="text" name="name" class="form-control" placeholder="Enter  Name" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer form_footer text-right">
                    <button type="submit" class="btn btn-success"><i class="far fa-save"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Add Record -->
<!-- Edit Record -->
<div id="edit_modal" class="modal fade" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-dialog-centered" permission="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Company</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form id="edit">
                <div class="card-body">
                    @csrf 
                    @method('PUT')
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="permission_name">Name:</label>
                                <input type="text" name="name" class="form-control" placeholder="Enter  Name" id="updatename" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer form_footer text-right">
                    <button type="submit" class="btn btn-success"><i class="far fa-save"></i> Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Edit Record -->
@endsection 
@section('scripts')
<script>
    var datatable;
    var rowid;
    $(document).ready(function () {
        // Fetching Records
        datatable = $("#datatable").DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ordering: false,
            ajax: {
                url: "{{url('company')}}",
                method: "get",
            },
            columns: [
                { data: "name" },
                { data: "action" },
            ],
            drawCallback: function (settings) {
                $(".edit").click(function () {
                    rowid = $(this).attr("id");
                    $("#updatename").val($(this).data("name"));
                    $("#edit_modal").modal("show");
                });
            },
        });
        // End Fetching Records
        // Adding Record
        $("#add").submit(function (e) {
            e.preventDefault();
            $.ajax({
                url: "{{route('company.store')}}",
                type: "post",
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function (success) {
                    if(success.errors){
                        $.each( success.errors, function( index, value ){
                            toastr.error(value);
                        });
                    }
                    else if(success.error_message){
                        toastr.error('An error has been occured! Please Contact Administrator.');
                    }
                    else{
                        datatable.ajax.reload();
                        document.getElementById("add").reset();
                        $("#add_new_modal").modal("hide");
                        toastr.success('Company has been Added Successfully!');
                    }
                },
                error: function (response) {
					toastr.error('Error! Company could not be created due to some reasons.');
				},
            });
        });
        // End Adding Record
        // Updating Record
        $("#edit").submit(function (e) {
            e.preventDefault();
            $.ajax({
                url: "{{url('company')}}" + "/" + rowid,
                type: "post",
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function (success) {
                    if(success.errors){
                        $.each( success.errors, function( index, value ){
                            toastr.error(value);
                        });
                    }
                    else if(success.error_message){
                        toastr.error('An error has been occured! Please Contact Administrator.');
                    }
                    else{
                        datatable.ajax.reload();
                        $("#edit_modal").modal("hide");
                        toastr.success('Company has been Updated Successfully!');
                    }
                },
                error: function (response) {
					toastr.error('Error! Company could not be updated due to some reasons.');
				},
            });
        });
        // End Updating Record
    });
    // Deleting Record
    function deleterow(id) {
        if (confirm("Do you really want to delete this Company?")) {
            $.ajax({
                url: "{{url('company')}}" + "/" + id,
                type: "delete",
                data: {
                    _token: "{{ csrf_token() }}",
                },
                success: function (success) {
                    if(success.error_message){
                        toastr.error('An error has been occured! Please Contact Administrator.');
                    }
                    else{
                        datatable.ajax.reload();
                        toastr.success('Company has been deleted Successfully!');
                    }
                },
                error: function (response) {
					toastr.error('Error! Company could not be deleted due to some reasons.');
				},
            });
        }
    }
    // End Deleting Record
</script>
@endsection